apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -c
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    app: account
  name: account
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    name: account
status:
  loadBalancer: {}
