apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -c
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    app: fastapi
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fastapi
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: fastapi
    spec:
      containers:
      - name: fastapi
        image: {{ .Values.image.fastapi }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        ports:
        - containerPort: 8000
        resources: {}
        volumeMounts:
        - mountPath: /logs
          name: logs
      restartPolicy: Always
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: logs
status: {}
