apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -c
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    app: fastapi
  name: fastapi
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    name: fastapi
status:
  loadBalancer: {}
