apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -c
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    app: fraud
  name: fraud
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    name: fraud
status:
  loadBalancer: {}
