apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -c
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    app: fraud
  name: fraud
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fraud
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: fraud
    spec:
      containers:
      - name: fraud
        image: {{ .Values.image.fraud }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: default
        ports:
        - containerPort: 8081
        resources: {}
        volumeMounts:
        - mountPath: /logs
          name: logs
      restartPolicy: Always
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: logs
status: {}
