---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fraud-microservice-service-monitor
spec:
  selector:
    matchLabels:
      app: fraud
  endpoints:
  - port: "8081"
    path: "/actuator/prometheus"